stages:
  - test
  - archive
  

  

tests:
  image: cirrusci/flutter
  stage: test
  before_script:
    - ls
    - cd \flutter_protyp
  script:
  - flutter test test/mainTest_test.dart




android:release:
  stage: archive
  image: cirrusci/flutter
  before_script:
    - cd \flutter_protyp
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --release
  artifacts:
    paths:
      - "**/**/**/**/**/**/*.apk"
    expire_in: 7 days


